// Mocks generated by Mockito 5.4.2 from annotations
// in mcu_quiz/test/features/quiz/domain/entities/quiz_mock_entity.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mcu_quiz/features/quiz/domain/entities/option_entity.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'quiz_mock_entity.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [QuizMockEntiy].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizMockEntiy extends _i1.Mock implements _i2.QuizMockEntiy {
  MockQuizMockEntiy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
      ) as int);
  @override
  String get question => (super.noSuchMethod(
        Invocation.getter(#question),
        returnValue: '',
      ) as String);
  @override
  List<_i3.OptionEntity> get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: <_i3.OptionEntity>[],
      ) as List<_i3.OptionEntity>);
  @override
  String get correctAnswer => (super.noSuchMethod(
        Invocation.getter(#correctAnswer),
        returnValue: '',
      ) as String);
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}
